---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fnf-files-pvc
  # kubectl config set-context local --namespace=fnf
  namespace: fnf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnf-deployment
  namespace: fnf
  labels:
    app: fnf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fnf
  template:
    metadata:
      labels:
        app: fnf
    spec:
      containers:
        - name: fnf-nginx
          image: webdevops/php-nginx:7.3-alpine
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: "/app"
            name: fnf-files
      volumes:
        - name: fnf-files
          persistentVolumeClaim:
            claimName: fnf-files-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fnf-service
  namespace: fnf
  labels:
    app: fnf
spec:
  ports:
    - port: 80
  selector:
    app: fnf
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fnf-ingress
  namespace: fnf
spec:
  rules:
    - host: www.thegeohunter.com
      http:
        paths:
        - backend:
            serviceName: fnf-service
            servicePort: 80
          path: /
    - host: thegeohunter.com
      http:
        paths:
        - backend:
            serviceName: fnf-service
            servicePort: 80
          path: /
  tls:
  - hosts:
    - www.thegeohunter.com
    - thegeohunter.com
    secretName: fnf-cert-tls
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  # kubectl cert-manager renew fnf-cert -n fnf
  name: fnf-cert
  namespace: fnf
spec:
  commonName: thegeohunter.com
  dnsNames:
    - www.thegeohunter.com
    - thegeohunter.com
  # kubectl describe certificate fnf-cert -n fnf
  secretName: fnf-cert-tls
  issuerRef:
    name: http-issuer
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
