---
apiVersion: v1
kind: ConfigMap
metadata:
  # kubectl config current-context
  name: example-configmap
  # kubectl config set-context local --namespace=example
  namespace: example
data:
  LOCALHOST: www.example.com
  APP_NAME: Example
  APP_VERSION: "1.0.0"