---
apiVersion: v1
kind: ConfigMap
metadata:
  # kubectl config current-context
  name: demox-configmap
  # kubectl config set-context local --namespace=demox
  namespace: demox
data:
  LOCALHOST: www.c4xp.ro
  APP_NAME: demox
  APP_VERSION: "1.0.0"
  DATABASE_URL: mysql-demox
  MYSQL_USER: demox_user
  MYSQL_DATABASE: demox_db