---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demox-mysql-pvc
  namespace: demox
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 2Gi
  # set only if you dont have a default storage-class
  # storageClassName: nfs-client
